# Generated by Django 4.1.2 on 2023-02-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
