# Generated by Django 4.1.2 on 2023-03-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='select_category',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid 19', 'Covid 19'), ('Imunization', 'Imunization ')], default='Covid 19', max_length=200),
            preserve_default=False,
        ),
    ]
